replicaCount: 1

image:
  repository: quiz-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  host: svc-cloudops.nhnent.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 500Mi

