replicaCount: 1

image:
  repository: quiz-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  host: svc-cloudops.nhnent.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 500Mi

oidc:
  enabled: true
  issuer: "https://sign-in.nhnent.com/auth/realms/nhn"
  clientId: "svccloudops"
  redirectUri: "https://svc-cloudops.nhnent.com/auth/callback"
  clientSecret: "3tGeNwlCi3HpIWz37z78LAFUxVfCSvBL"
  sessionSecret: "CHANGE_ME_RANDOM_STRING"

