apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-app-config
  namespace: quiz-app
  labels:
    app: quiz-app
data:
  OIDC_ENABLED: "true"
  OIDC_ISSUER: "https://sign-in.nhnent.com/auth/realms/nhn"
  OIDC_CLIENT_ID: "svccloudops"
  OIDC_REDIRECT_URI: "https://svc-cloudops.nhnent.com/auth/callback"
