apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quiz-app-ingress
  namespace: quiz-app
  labels:
    app: quiz-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: svc-cloudops.nhnent.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quiz-app-svc
                port:
                  number: 8000
