apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-platform

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: infra-platform
    includeSelectors: false
    includeTemplates: false
