apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-app-pvc
  namespace: quiz-app
  labels:
    app: quiz-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
