apiVersion: v1
kind: Secret
metadata:
  name: quiz-app-secret
  namespace: quiz-app
  labels:
    app: quiz-app
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: "3tGeNwlCi3HpIWz37z78LAFUxVfCSvBL"
  SESSION_SECRET: "CHANGE_ME_RANDOM_STRING"
