apiVersion: v1
kind: Service
metadata:
  name: quiz-app-svc
  namespace: quiz-app
  labels:
    app: quiz-app
spec:
  type: ClusterIP
  selector:
    app: quiz-app
  ports:
    - port: 8000
      targetPort: 8000
