apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quiz-app.fullname" . }}-config
  labels:
    {{- include "quiz-app.labels" . | nindent 4 }}
data:
  OIDC_ENABLED: {{ .Values.oidc.enabled | quote }}
  OIDC_ISSUER: {{ .Values.oidc.issuer | quote }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  OIDC_REDIRECT_URI: {{ .Values.oidc.redirectUri | quote }}
