apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quiz-app.fullname" . }}-deployment
  labels:
    {{- include "quiz-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      {{- include "quiz-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quiz-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: quiz-data
              mountPath: /app/data
            - name: quiz-questions
              mountPath: /app/questions
          readinessProbe:
            httpGet:
              path: /api/rounds
              port: {{ .Values.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/rounds
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 15
      volumes:
        - name: quiz-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "quiz-app.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: quiz-questions
          configMap:
            name: {{ include "quiz-app.fullname" . }}-questions
