apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quiz-app.fullname" . }}-secret
  labels:
    {{- include "quiz-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  SESSION_SECRET: {{ .Values.oidc.sessionSecret | quote }}
